### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by dagurval**

### CODE REVIEW

**Comment by zander** [comment]
These changes look good. The Use assertEqual instead of assertEquals will stay backwards compatible?

Unfortunately you and ftrader opened a PR at approx the same time and I merged his before I saw yours.

I'll check on slack if his is made with a simple tool that can be re-run as I can tell yours are manual changes.

**Comment by ftrader** [comment]
@zander : I mentioned the tool in my PR (`autopep8`). I also added a manual change for some comment linebreaking and replacement of `if (var == True):` with the slightly more Pythonic `if var is True:`.
Fun fact: I was just working on a followup commit to PR#1 to do the parentheses removals, but you merged before I got a chance to commit, and then I noticed this PR had made those as well.

@dagurval has some very nice changes here re: replacement of constants etc.
Suggest you merge those bits but run pep8 to check that the files are clean.

I wonder if one could easily configure Travis for this repo to run Python-specific checks if it sees modifications in the `python` directory. It would be trivial to set up a Travis file to do those Python specific checks. Of course the best would be to exercise all languages...

**Comment by zander** [comment]
OK, I merged this one after reverting PR1 and then afterwards I ran the autopip8 tool on the result. So I ended up using both your work :)

What kind of python checks are you thinking of? The Classic project has a Teamcity continues integration server that is 100% reserved for Classic. For security that isn't public, so I guess many people don't realize this.

If you have any specific suggestions for tests, please share them.

**Comment by ftrader** [comment]
>What kind of python checks are you thinking of?

The kind where a PR or commit here results in automated tests of the binding suite, and allows a submitter to easily see that they didn't break anything since the build results are public & can be directly integrated with GitHub.

For the Python binding, that could just execute runtests.py.

I was thinking of, minimally, a top-level build file that tries to compile all compilable bindings and runs all the existing test programs.

Doesn't matter whether one uses Teamcity or Travis, that would be generally useful.

**Pull request merged**
